# Generated by Django 5.0.7 on 2024-07-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_commonexpense_remove_transaction_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_common_expense',
            field=models.BooleanField(default=False),
        ),
    ]
