# Generated by Django 5.0.7 on 2024-07-16 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_is_common_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_common_expense',
        ),
        migrations.AddField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
