# Generated by Django 5.0.7 on 2024-07-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_transaction_is_common_expense_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonExpense',
        ),
    ]
