# Generated by Django 5.0.7 on 2024-07-16 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_delete_commonexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_expense',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.project'),
        ),
    ]
